// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/recipes.tsx";
import * as $4 from "./routes/blog/[blog].tsx";
import * as $5 from "./routes/countdown.tsx";
import * as $6 from "./routes/github/[username].tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/recipe.tsx";
import * as $9 from "./routes/recipes/[recipe].tsx";
import * as $10 from "./routes/recipes/index.tsx";
import * as $11 from "./routes/search.tsx";
import * as $$0 from "./islands/Coundown.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/recipes.tsx": $3,
    "./routes/blog/[blog].tsx": $4,
    "./routes/countdown.tsx": $5,
    "./routes/github/[username].tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/recipe.tsx": $8,
    "./routes/recipes/[recipe].tsx": $9,
    "./routes/recipes/index.tsx": $10,
    "./routes/search.tsx": $11,
  },
  islands: {
    "./islands/Coundown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
